### ISSUE TITLE
Eu como cliente desejo ter os links e descrição das pesquisas para analisá-los ao longo do tempo

### ISSUE THREAD

**Issue by ricardorachaus** [unb-cic-esw/Observatorio-google#6]
Critérios de aceitação:

1 - Obter os dados ao longo do tempo
2 - Legalidade do ato
3 - Persistência dos dados

**Comment by leooleo** [comment]
Os dados são persistidos pelo programa na pasta resultados. A coletânea dos dados capturados(tanto pelo Scrapper quanto a API) serão armazenados no link: https://drive.google.com/drive/folders/1nLoSv_L3XqKvq-sOaC3O47EoYXy7dtrA?usp=sharing
